# Generated by Django 4.1.7 on 2023-02-23 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('origine', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('ATTENTE', 'attente'), ('EN COURS', 'En cours de livraison'), ('LIVRE', 'Livré')], max_length=50)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('stock', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField()),
            ],
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('quater', models.CharField(max_length=200)),
                ('codepostal', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Tricycle',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('chassis', models.IntegerField()),
                ('cylindre', models.FloatField()),
                ('nbre_vitesse', models.IntegerField(blank=True)),
                ('vignette', models.BooleanField(default=False)),
                ('type_model', models.CharField(max_length=20)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tension_batterie', models.DecimalField(decimal_places=2, max_digits=7)),
                ('puissance_admin', models.FloatField()),
                ('capacite_recervoir', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nbre_place', models.IntegerField()),
                ('coulour', models.CharField(max_length=20)),
                ('wheels_number', models.IntegerField(default=3)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.brand')),
            ],
            options={
                'abstract': False,
            },
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='MotorBike',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('chassis', models.IntegerField()),
                ('cylindre', models.FloatField()),
                ('nbre_vitesse', models.IntegerField(blank=True)),
                ('vignette', models.BooleanField(default=False)),
                ('type_model', models.CharField(max_length=20)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tension_batterie', models.DecimalField(decimal_places=2, max_digits=7)),
                ('puissance_admin', models.FloatField()),
                ('capacite_recervoir', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nbre_place', models.IntegerField()),
                ('coulour', models.CharField(max_length=20)),
                ('motor_warranty', models.IntegerField(blank=True, null=True)),
                ('usage', models.CharField(choices=[('VILLE', 'ville'), ('COMMERCIAL', 'commercial'), ('AVENTURE', 'aventure')], max_length=30)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.brand')),
            ],
            options={
                'abstract': False,
            },
            bases=('store.product',),
        ),
    ]
