# Generated by Django 4.1.3 on 2022-11-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ATTENTE', 'attente'), ('EN COURS', 'En cours de livraison'), ('LIVRE', 'Livré')], default='attente', max_length=50),
            preserve_default=False,
        ),
    ]
