# Generated by Django 4.1.7 on 2023-02-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_motorbike_genre_tricycle_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorbike',
            name='genre',
            field=models.CharField(default='Moto', max_length=50),
        ),
        migrations.AlterField(
            model_name='tricycle',
            name='genre',
            field=models.CharField(default='Tricycle', max_length=50),
        ),
    ]
