# Generated by Django 4.1.7 on 2023-02-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_motorbike_genre_alter_tricycle_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorbike',
            name='description',
            field=models.TextField(blank=True, default='No description', null=True),
        ),
        migrations.AddField(
            model_name='tricycle',
            name='description',
            field=models.TextField(blank=True, default='No description', null=True),
        ),
        migrations.AlterField(
            model_name='motorbike',
            name='genre',
            field=models.CharField(default='Moto', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='tricycle',
            name='genre',
            field=models.CharField(default='Tricycle', editable=False, max_length=50),
        ),
    ]
