# Generated by Django 4.1.7 on 2023-03-10 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='No description', null=True)),
                ('parent_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.categorie')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.subcategorie'),
        ),
    ]
