# Generated by Django 4.1.7 on 2023-03-10 18:13

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_subcategorie_product_subcategorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategorie',
        ),
        migrations.AddField(
            model_name='categorie',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.categorie'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='name', unique=True),
        ),
        migrations.DeleteModel(
            name='Subcategorie',
        ),
    ]
