# Generated by Django 4.1.7 on 2023-03-10 18:19

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_product_subcategorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
