# Generated by Django 4.1.7 on 2023-06-19 08:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_categorie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
