# Generated by Django 4.1.7 on 2023-06-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_categorie_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'verbose_name_plural': 'Accessoires'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Marques'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='motorbike',
            options={'verbose_name_plural': 'Motocylettes'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Commandes'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Adresses de livraison'},
        ),
        migrations.AlterModelOptions(
            name='tricycle',
            options={'verbose_name_plural': 'Tricycles'},
        ),
        migrations.RemoveField(
            model_name='motorbike',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='tricycle',
            name='genre',
        ),
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
