# Generated by Django 4.1.7 on 2023-09-19 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_categorie_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'verbose_name_plural': 'Accessoires'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Marques'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='motorbike',
            options={'verbose_name_plural': 'Motocylettes'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Commandes'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Adresses de livraison'},
        ),
        migrations.AlterModelOptions(
            name='tricycle',
            options={'verbose_name_plural': 'Tricycles'},
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='motorbike',
            name='description',
        ),
        migrations.RemoveField(
            model_name='motorbike',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='tricycle',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tricycle',
            name='genre',
        ),
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='No description', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
        ),
    ]
