# Generated by Django 4.1.7 on 2023-09-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_images_product_gallery_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gallery_images',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
