# Generated by Django 4.1.7 on 2023-10-15 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_categorie_logo_delete_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('type_model', models.CharField(max_length=20)),
                ('chassis', models.PositiveIntegerField()),
                ('cylindre', models.FloatField()),
                ('nbre_vitesse', models.PositiveIntegerField(blank=True)),
                ('vignette', models.BooleanField(default=False)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tension_batterie', models.DecimalField(decimal_places=2, max_digits=7)),
                ('puissance_admin', models.FloatField()),
                ('capacite_recervoir', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nbre_place', models.PositiveIntegerField()),
                ('coulour', models.CharField(max_length=20)),
                ('motor_warranty', models.PositiveIntegerField(blank=True, null=True)),
                ('usage', models.CharField(blank=True, choices=[('VILLE', 'ville'), ('COMMERCIAL', 'commercial'), ('AVENTURE', 'aventure')], max_length=30, null=True)),
                ('wheels_number', models.PositiveIntegerField(default=2)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.brand')),
            ],
            bases=('store.product',),
        ),
        migrations.RemoveField(
            model_name='images',
            name='product',
        ),
        migrations.RemoveField(
            model_name='motorbike',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='motorbike',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tricycle',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='tricycle',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=50)),
                ('moto_cible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.moto')),
            ],
            bases=('store.product',),
        ),
        migrations.DeleteModel(
            name='Accessory',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='MotorBike',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='Tricycle',
        ),
    ]
