# Generated by Django 4.1.7 on 2023-10-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_moto_remove_images_product_remove_motorbike_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='origine',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
