# Generated by Django 4.1.7 on 2023-10-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_rename_brand_equipement_fabirquant'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='annee',
            field=models.PositiveIntegerField(default=2018),
            preserve_default=False,
        ),
    ]
