# Generated by Django 4.1.7 on 2023-10-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.FileField(blank=True, upload_to='products_images/'),
        ),
    ]
