# Generated by Django 4.1.7 on 2023-11-22 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_productvariation_color_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariationImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('images', models.FileField(blank=True, upload_to='variation_images/')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productvariation')),
            ],
        ),
    ]
