# Generated by Django 4.1.7 on 2024-01-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_variationimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='value',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='variation_type',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='size',
            field=models.CharField(default='xl', max_length=20),
            preserve_default=False,
        ),
    ]
