# Generated by Django 4.1.7 on 2023-11-18 06:49

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_username_user_numero_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numero_telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
